packages:
  - packages/*

catalog:
  '@custom-elements-manifest/analyzer': 0.10.10
  '@esm-bundle/chai': 4.3.4-fix.0
  '@open-wc/testing': 4.0.0
  '@storybook/addon-a11y': 9.1.12
  '@storybook/addon-docs': 9.1.12
  '@storybook/addon-links': 9.1.12
  '@storybook/addon-themes': 9.1.12
  '@storybook/web-components-vite': 9.1.12
  '@tylertech-eslint/eslint-plugin': 3.0.0
  '@tylertech/forge': 3.11.0
  '@tylertech/stylelint-rules': 5.1.2
  '@tylertech/tyler-icons': 2.0.4
  '@types/mocha': 10.0.10
  '@types/node': 24.8.0
  '@types/sinon': 17.0.4
  '@vueless/storybook-dark-mode': 9.0.9
  '@web/dev-server-esbuild': 1.0.4
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.20.2
  '@web/test-runner-commands': 0.9.0
  '@web/test-runner-junit-reporter': 0.8.0
  '@web/test-runner-playwright': 0.11.1
  eslint: 9.37.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  glob: 11.0.3
  lit: 3.3.1
  lit-analyzer: 2.0.3
  plop: 4.0.4
  postcss-lit: 1.3.1
  prettier: 3.6.2
  remark-gfm: 4.0.1
  rimraf: 6.0.1
  sass: 1.93.2
  sinon: 21.0.0
  storybook: 9.1.12
  stylelint: 16.25.0
  stylelint-config-standard: 39.0.1
  tslib: 2.8.1
  vite: 7.1.10
  vite-plugin-dts: 4.5.4
  vite-tsconfig-paths: 5.1.4
