packages:
  - packages/*

catalog:
  '@custom-elements-manifest/analyzer': 0.11.0
  '@esm-bundle/chai': 4.3.4-fix.0
  '@open-wc/testing': 4.0.0
  '@storybook/addon-a11y': 9.1.17
  '@storybook/addon-docs': 9.1.17
  '@storybook/addon-links': 9.1.17
  '@storybook/addon-themes': 9.1.17
  '@storybook/web-components-vite': 9.1.17
  '@tylertech-eslint/eslint-plugin': 3.0.0
  '@tylertech/forge': 3.13.1
  '@tylertech/stylelint-rules': 5.1.2
  '@tylertech/tyler-icons': 2.0.4
  '@types/mocha': 10.0.10
  '@types/node': 25.0.3
  '@types/sinon': 21.0.0
  '@vueless/storybook-dark-mode': 9.0.10
  '@web/dev-server-esbuild': 1.0.4
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.20.2
  '@web/test-runner-commands': 0.9.0
  '@web/test-runner-junit-reporter': 0.8.0
  '@web/test-runner-playwright': 0.11.1
  eslint: 9.39.2
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  glob: 13.0.0
  lit: 3.3.2
  lit-analyzer: 2.0.3
  plop: 4.0.4
  postcss-lit: 1.3.1
  prettier: 3.7.4
  remark-gfm: 4.0.1
  rimraf: 6.1.2
  sass: 1.93.3
  sinon: 21.0.1
  storybook: 9.1.17
  stylelint: 16.26.1
  stylelint-config-standard: 39.0.1
  tslib: 2.8.1
  vite: 7.3.0
  vite-plugin-dts: 4.5.4
  vite-tsconfig-paths: 6.0.3
