import type { ReactElement } from 'react';
import {
  JSONUIProvider,
  Renderer as JsonRenderer,
  type Spec,
  type ComponentRegistry,
  type ComponentRenderer
} from '@json-render/react';
import { builtInValidationFunctions, type ComputedFunction } from '@tylertech/agent-ui';

export interface RendererProps {
  /** The UI specification to render (typically generated by an AI model) */
  spec: Spec;
  /** Registry mapping component types to React implementations */
  registry: ComponentRegistry;
  /** Action handlers invoked when components trigger actions (e.g., button clicks) */
  handlers?: Record<string, (params: Record<string, unknown>) => Promise<unknown> | unknown>;
  /** Initial state values merged with spec.state (initialState takes precedence) */
  initialState?: Record<string, unknown>;
  /** Callback fired when state changes occur within the rendered UI */
  onStateChange?: (changes: Array<{ path: string; value: unknown }>) => void;
  /** Custom computed functions available via $computed expressions in the spec */
  functions?: Record<string, ComputedFunction>;
  /** When true, indicates the spec is still streaming (components may show loading states) */
  loading?: boolean;
  /** Fallback renderer for unknown component types */
  fallback?: ComponentRenderer;
}

/**
 * Renders a UI specification using the provided component registry.
 *
 * Wraps the @json-render/react Renderer with a JSONUIProvider to enable
 * state management, action handling, and computed functions.
 *
 * @example
 * ```tsx
 * <Renderer
 *   spec={spec}
 *   registry={registry}
 *   handlers={{ save: async (data) => api.save(data) }}
 *   loading={isStreaming}
 * />
 * ```
 */
export function Renderer({
  spec,
  registry,
  handlers,
  initialState,
  onStateChange,
  functions,
  loading,
  fallback
}: RendererProps): ReactElement {
  const mergedInitialState = { ...(spec.state ?? {}), ...(initialState ?? {}) };

  return (
    <JSONUIProvider
      registry={registry}
      initialState={mergedInitialState}
      handlers={handlers}
      validationFunctions={builtInValidationFunctions}
      functions={functions}
      onStateChange={onStateChange}>
      <JsonRenderer spec={spec} registry={registry} loading={loading} fallback={fallback} />
    </JSONUIProvider>
  );
}
