name: Changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup pnpm
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          pr-title: "chore: release"
          commit-message: "chore: release"
          publish-script: pnpm run release
          version-script: pnpm run changeset:version
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
